-- Bloqueio de força bruta e trilha de segurança do login do aplicativo.
-- Execute esta migration no SQL Editor do Supabase antes de considerar o hardening concluído.

create table if not exists public.login_security_events (
  id bigint generated by default as identity primary key,
  email_hash text not null,
  ip_hash text not null,
  user_agent_hash text,
  user_id uuid references public.app_users(id) on delete set null,
  success boolean not null default false,
  blocked boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists login_security_events_email_created_idx
  on public.login_security_events (email_hash, created_at desc);
create index if not exists login_security_events_ip_created_idx
  on public.login_security_events (ip_hash, created_at desc);
create index if not exists login_security_events_created_idx
  on public.login_security_events (created_at desc);

alter table public.login_security_events enable row level security;
revoke all on table public.login_security_events from public, anon, authenticated;

create or replace function public.login_app_user_secure(
  p_email text,
  p_password text,
  p_ip_hash text default 'direct',
  p_user_agent_hash text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.app_users%rowtype;
  v_email text;
  v_email_hash text;
  v_ip_hash text;
  v_user_agent_hash text;
  v_failed_attempts integer;
  v_last_success timestamptz;
  v_valid_password boolean := false;
  v_token text;
  v_expires_at timestamptz;
begin
  v_email := lower(left(trim(coalesce(p_email, '')), 254));
  v_email_hash := encode(extensions.digest(convert_to(v_email, 'UTF8'), 'sha256'), 'hex');
  v_ip_hash := left(coalesce(nullif(trim(p_ip_hash), ''), 'direct'), 128);
  v_user_agent_hash := left(nullif(trim(coalesce(p_user_agent_hash, '')), ''), 128);

  -- Serializa tentativas para o mesmo e-mail/IP e reduz bypass por concorrência.
  perform pg_advisory_xact_lock(hashtextextended(v_email_hash, 0));
  perform pg_advisory_xact_lock(hashtextextended(v_ip_hash, 1));

  select max(created_at)
  into v_last_success
  from public.login_security_events
  where success = true
    and (email_hash = v_email_hash or (v_ip_hash <> 'direct' and ip_hash = v_ip_hash));

  select count(*)::integer
  into v_failed_attempts
  from public.login_security_events
  where success = false
    and created_at > greatest(
      now() - interval '15 minutes',
      coalesce(v_last_success, '-infinity'::timestamptz)
    )
    and (email_hash = v_email_hash or (v_ip_hash <> 'direct' and ip_hash = v_ip_hash));

  if v_failed_attempts >= 5 then
    insert into public.login_security_events (
      email_hash, ip_hash, user_agent_hash, success, blocked
    ) values (
      v_email_hash, v_ip_hash, v_user_agent_hash, false, true
    );
    return jsonb_build_object(
      'ok', false,
      'code', 'RATE_LIMITED',
      'error', 'Muitas tentativas. Aguarde 15 minutos e tente novamente.',
      'retryAfter', 900
    );
  end if;

  select *
  into v_user
  from public.app_users
  where lower(email) = v_email
    and active = true
  limit 1;

  if v_user.id is null then
    -- Equaliza parcialmente o custo entre e-mail existente e inexistente.
    perform extensions.crypt(coalesce(p_password, ''), extensions.gen_salt('bf', 10));
  else
    v_valid_password := v_user.password_hash = extensions.crypt(coalesce(p_password, ''), v_user.password_hash);
  end if;

  if v_user.id is null or not v_valid_password then
    insert into public.login_security_events (
      email_hash, ip_hash, user_agent_hash, user_id, success, blocked
    ) values (
      v_email_hash, v_ip_hash, v_user_agent_hash, v_user.id, false, false
    );
    return jsonb_build_object(
      'ok', false,
      'code', 'INVALID_CREDENTIALS',
      'error', 'Login ou senha inválidos.'
    );
  end if;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');
  v_expires_at := now() + interval '8 hours';

  delete from public.app_sessions where expires_at <= now();

  insert into public.app_sessions (user_id, token_hash, expires_at)
  values (
    v_user.id,
    encode(extensions.digest(convert_to(v_token, 'UTF8'), 'sha256'), 'hex'),
    v_expires_at
  );

  -- Mantém no máximo cinco sessões simultâneas por usuário.
  delete from public.app_sessions
  where user_id = v_user.id
    and id in (
      select id
      from public.app_sessions
      where user_id = v_user.id
      order by created_at desc
      offset 5
    );

  insert into public.login_security_events (
    email_hash, ip_hash, user_agent_hash, user_id, success, blocked
  ) values (
    v_email_hash, v_ip_hash, v_user_agent_hash, v_user.id, true, false
  );

  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (
    v_user.id,
    'app_user',
    v_user.id::text,
    'login',
    jsonb_build_object('ipHash', left(v_ip_hash, 16))
  );

  return jsonb_build_object(
    'ok', true,
    'session', jsonb_build_object(
      'token', v_token,
      'expiresAt', v_expires_at,
      'user', jsonb_build_object(
        'id', v_user.id,
        'email', v_user.email,
        'name', v_user.name,
        'role', v_user.role
      )
    )
  );
end;
$$;

-- A assinatura antiga permanece apenas para chamadas internas do backend.
create or replace function public.login_app_user(p_email text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  v_result := public.login_app_user_secure(
    p_email,
    p_password,
    'server-internal',
    null
  );
  if coalesce((v_result ->> 'ok')::boolean, false) then
    return v_result -> 'session';
  end if;
  return v_result;
end;
$$;

revoke execute on function public.login_app_user_secure(text, text, text, text) from public, anon, authenticated;
revoke execute on function public.login_app_user(text, text) from public, anon, authenticated;
grant execute on function public.login_app_user_secure(text, text, text, text) to service_role;
grant execute on function public.login_app_user(text, text) to service_role;

-- Helpers internos não precisam permanecer expostos pelo PostgREST.
revoke execute on function public.current_app_user_id(text) from public, anon, authenticated;
revoke execute on function public.require_app_user(text) from public, anon, authenticated;
revoke execute on function public.is_platform_admin(uuid) from public, anon, authenticated;
revoke execute on function public.can_access_tenant(uuid, uuid) from public, anon, authenticated;
revoke execute on function public.can_manage_tenant(uuid, uuid) from public, anon, authenticated;
revoke execute on function public.require_platform_admin(text) from public, anon, authenticated;
revoke execute on function public.require_unit_access(uuid, text, boolean) from public, anon, authenticated;
revoke execute on function public.authorize_tenant_file(text, uuid, text, text) from public, anon, authenticated;
grant execute on function public.authorize_tenant_file(text, uuid, text, text) to service_role;

comment on table public.login_security_events is
  'Eventos de autenticação pseudonimizados para bloqueio de força bruta e investigação.';
