create table if not exists public.tenants (
  id uuid primary key default extensions.gen_random_uuid(),
  code text not null unique,
  name text not null,
  status text not null default 'active' check (status in ('active', 'suspended', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tenants enable row level security;

drop trigger if exists touch_tenants_updated_at on public.tenants;
create trigger touch_tenants_updated_at before update on public.tenants
for each row execute function public.touch_updated_at();

alter table public.units add column if not exists tenant_id uuid references public.tenants(id) on delete restrict;

insert into public.tenants (code, name)
select u.id, coalesce(nullif(u.name, ''), upper(u.city))
from public.units u
on conflict (code) do update set name = excluded.name;

update public.units u
set tenant_id = t.id
from public.tenants t
where t.code = u.id
  and u.tenant_id is null;

alter table public.units alter column tenant_id set not null;

create index if not exists units_tenant_id_idx on public.units(tenant_id);

create table if not exists public.tenant_memberships (
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  user_id uuid not null references public.app_users(id) on delete cascade,
  role text not null default 'user' check (role in ('franchise_admin', 'manager', 'user')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, user_id)
);

alter table public.tenant_memberships enable row level security;

drop trigger if exists touch_tenant_memberships_updated_at on public.tenant_memberships;
create trigger touch_tenant_memberships_updated_at before update on public.tenant_memberships
for each row execute function public.touch_updated_at();

create index if not exists tenant_memberships_user_id_idx on public.tenant_memberships(user_id);

create table if not exists public.module_catalog (
  code text primary key,
  name text not null,
  description text not null,
  sort_order integer not null default 0,
  default_enabled boolean not null default false,
  active boolean not null default true
);

alter table public.module_catalog enable row level security;

insert into public.module_catalog (code, name, description, sort_order, default_enabled) values
  ('business', 'Negócios', 'Implantação, roadmap, compras, documentos e credenciamentos.', 10, true),
  ('hr', 'Recursos Humanos', 'Vagas, candidatos, triagem e entrevistas.', 20, false),
  ('dp', 'Departamento Pessoal', 'Colaboradores, admissões, folha e obrigações.', 30, false),
  ('accounting', 'Contabilidade', 'Documentos fiscais, competências, guias e balancetes.', 40, false),
  ('finance', 'Financeiro', 'Contas, fluxo de caixa, orçamento e indicadores.', 50, false)
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    default_enabled = excluded.default_enabled,
    active = true;

create table if not exists public.tenant_modules (
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  module_code text not null references public.module_catalog(code) on delete restrict,
  status text not null default 'locked' check (status in ('locked', 'requested', 'active', 'suspended')),
  enabled_at timestamptz,
  enabled_by uuid references public.app_users(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (tenant_id, module_code)
);

alter table public.tenant_modules enable row level security;

drop trigger if exists touch_tenant_modules_updated_at on public.tenant_modules;
create trigger touch_tenant_modules_updated_at before update on public.tenant_modules
for each row execute function public.touch_updated_at();

insert into public.tenant_modules (tenant_id, module_code, status, enabled_at)
select t.id, m.code, case when m.default_enabled then 'active' else 'locked' end,
       case when m.default_enabled then now() else null end
from public.tenants t
cross join public.module_catalog m
on conflict (tenant_id, module_code) do nothing;

create table if not exists public.module_requests (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  module_code text not null references public.module_catalog(code) on delete restrict,
  requested_by uuid not null references public.app_users(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  notes text,
  reviewed_by uuid references public.app_users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.module_requests enable row level security;
create index if not exists module_requests_tenant_status_idx on public.module_requests(tenant_id, status);
create unique index if not exists module_requests_one_pending_idx
on public.module_requests(tenant_id, module_code) where status = 'pending';

create table if not exists public.membership_module_permissions (
  tenant_id uuid not null,
  user_id uuid not null,
  module_code text not null references public.module_catalog(code) on delete cascade,
  can_view boolean not null default true,
  can_edit boolean not null default false,
  can_approve boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, user_id, module_code),
  foreign key (tenant_id, user_id) references public.tenant_memberships(tenant_id, user_id) on delete cascade
);

alter table public.membership_module_permissions enable row level security;

drop trigger if exists touch_membership_module_permissions_updated_at on public.membership_module_permissions;
create trigger touch_membership_module_permissions_updated_at before update on public.membership_module_permissions
for each row execute function public.touch_updated_at();

create or replace function public.is_platform_admin(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.app_users u
    where u.id = p_user_id
      and u.active = true
      and lower(u.role) in ('admin', 'platform_admin')
  );
$$;

create or replace function public.can_access_tenant(p_user_id uuid, p_tenant_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_platform_admin(p_user_id) or exists (
    select 1
    from public.tenant_memberships tm
    join public.tenants t on t.id = tm.tenant_id
    where tm.user_id = p_user_id
      and tm.tenant_id = p_tenant_id
      and tm.active = true
      and t.status = 'active'
  );
$$;

create or replace function public.can_manage_tenant(p_user_id uuid, p_tenant_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_platform_admin(p_user_id) or exists (
    select 1
    from public.tenant_memberships tm
    where tm.user_id = p_user_id
      and tm.tenant_id = p_tenant_id
      and tm.active = true
      and tm.role in ('franchise_admin', 'manager')
  );
$$;

create or replace function public.require_platform_admin(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
begin
  v_user_id := public.require_app_user(p_token);
  if not public.is_platform_admin(v_user_id) then
    raise exception 'Acesso permitido somente para administradores da plataforma' using errcode = '42501';
  end if;
  return v_user_id;
end;
$$;

create or replace function public.require_unit_access(p_user_id uuid, p_unit_id text, p_manage boolean default false)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant_id uuid;
begin
  select tenant_id into v_tenant_id from public.units where id = p_unit_id;
  if v_tenant_id is null then
    raise exception 'Franquia não encontrada' using errcode = 'P0002';
  end if;
  if p_manage and not public.can_manage_tenant(p_user_id, v_tenant_id) then
    raise exception 'Você não possui permissão para alterar esta franquia' using errcode = '42501';
  elsif not p_manage and not public.can_access_tenant(p_user_id, v_tenant_id) then
    raise exception 'Você não possui acesso a esta franquia' using errcode = '42501';
  end if;
  return v_tenant_id;
end;
$$;

create or replace function public.get_portal_data(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_is_admin boolean;
begin
  v_user_id := public.require_app_user(p_token);
  v_is_admin := public.is_platform_admin(v_user_id);

  return jsonb_build_object(
    'generatedAt', now(),
    'sourceFiles', coalesce((
      select jsonb_agg(distinct u.source_file)
      from public.units u
      where u.source_file is not null and (v_is_admin or public.can_access_tenant(v_user_id, u.tenant_id))
    ), '[]'::jsonb),
    'userProfile', coalesce((
      select jsonb_build_object(
        'name', coalesce(nullif(p.display_name, ''), nullif(u.name, ''), split_part(u.email, '@', 1), 'Usuário'),
        'photo', coalesce(p.photo_data, '')
      )
      from public.app_users u
      left join public.app_user_profiles p on p.user_id = u.id
      where u.id = v_user_id
    ), jsonb_build_object('name', 'Usuário', 'photo', '')),
    'accessContext', jsonb_build_object(
      'platformAdmin', v_is_admin,
      'memberships', coalesce((
        select jsonb_agg(jsonb_build_object(
          'tenantId', tm.tenant_id,
          'tenantName', t.name,
          'tenantCode', t.code,
          'role', tm.role,
          'permissions', coalesce((
            select jsonb_agg(jsonb_build_object(
              'moduleCode', mp.module_code,
              'canView', mp.can_view,
              'canEdit', mp.can_edit,
              'canApprove', mp.can_approve
            ) order by mp.module_code)
            from public.membership_module_permissions mp
            where mp.tenant_id = tm.tenant_id and mp.user_id = tm.user_id
          ), '[]'::jsonb)
        ) order by t.name)
        from public.tenant_memberships tm
        join public.tenants t on t.id = tm.tenant_id
        where tm.user_id = v_user_id and tm.active = true
      ), '[]'::jsonb)
    ),
    'tenantModules', coalesce((
      select jsonb_agg(jsonb_build_object(
        'tenantId', tm.tenant_id,
        'moduleCode', tm.module_code,
        'name', mc.name,
        'description', mc.description,
        'status', tm.status
      ) order by mc.sort_order, mc.name)
      from public.tenant_modules tm
      join public.module_catalog mc on mc.code = tm.module_code
      where mc.active = true and (v_is_admin or public.can_access_tenant(v_user_id, tm.tenant_id))
    ), '[]'::jsonb),
    'units', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', u.id,
        'tenantId', u.tenant_id,
        'name', u.name,
        'city', u.city,
        'state', coalesce(u.state, ''),
        'franchisee', coalesce(u.franchisee, ''),
        'openingDate', coalesce(u.opening_date::text, ''),
        'sourceFile', coalesce(u.source_file, ''),
        'ownerName', coalesce(u.owner_name, ''),
        'priority', coalesce(u.priority, 'Normal'),
        'tasks', coalesce((
          select jsonb_agg(jsonb_build_object(
            'id', r.id, 'item', coalesce(r.item, ''), 'phase', r.phase, 'process', r.process,
            'status', r.status, 'deadline', coalesce(r.deadline::text, ''),
            'actualDate', coalesce(r.actual_date::text, ''), 'notes', coalesce(r.notes, '')
          ) order by r.sort_order, r.item, r.process)
          from public.roadmap_tasks r where r.unit_id = u.id
        ), '[]'::jsonb),
        'purchases', coalesce((
          select jsonb_agg(jsonb_build_object(
            'id', p.id, 'item', p.item, 'status', p.status, 'notes', coalesce(p.notes, '')
          ) order by p.sort_order, p.item)
          from public.purchase_items p where p.unit_id = u.id
        ), '[]'::jsonb)
      ) order by u.city, u.state)
      from public.units u
      where v_is_admin or public.can_access_tenant(v_user_id, u.tenant_id)
    ), '[]'::jsonb),
    'operationalRecords', coalesce((
      select jsonb_agg(jsonb_build_object(
        'unitId', r.unit_id, 'recordType', r.record_type, 'recordId', r.record_id, 'hidden', r.hidden
      ) || r.payload order by r.updated_at desc)
      from public.unit_operational_records r
      join public.units u on u.id = r.unit_id
      where v_is_admin or public.can_access_tenant(v_user_id, u.tenant_id)
    ), '[]'::jsonb),
    'accreditation', jsonb_build_object(
      'sourceFile', 'Supabase',
      'units', coalesce((
        select jsonb_agg(jsonb_build_object('id', au.id, 'name', au.name, 'owner', coalesce(au.owner_name, '')) order by au.name)
        from public.accreditation_units au
        left join public.units u on u.id = au.id
        where v_is_admin or (u.id is not null and public.can_access_tenant(v_user_id, u.tenant_id))
      ), '[]'::jsonb),
      'procedures', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', ap.id,
          'group', ap.group_name,
          'name', ap.name,
          'statuses', coalesce((
            select jsonb_object_agg(acs.unit_id, acs.status)
            from public.accreditation_statuses acs
            left join public.units u on u.id = acs.unit_id
            where acs.procedure_id = ap.id
              and not coalesce(acs.hidden, false)
              and (v_is_admin or (u.id is not null and public.can_access_tenant(v_user_id, u.tenant_id)))
          ), '{}'::jsonb),
          'details', coalesce((
            select jsonb_object_agg(acs.unit_id, jsonb_build_object(
              'status', acs.status,
              'requestDate', coalesce(acs.request_date::text, ''),
              'approvalDate', coalesce(acs.approval_date::text, ''),
              'owner', coalesce(acs.owner_name, ''),
              'attachments', coalesce(acs.attachments, ''),
              'notes', coalesce(acs.notes, ''),
              'hidden', coalesce(acs.hidden, false)
            ))
            from public.accreditation_statuses acs
            left join public.units u on u.id = acs.unit_id
            where acs.procedure_id = ap.id
              and (v_is_admin or (u.id is not null and public.can_access_tenant(v_user_id, u.tenant_id)))
          ), '{}'::jsonb)
        ) order by ap.sort_order, ap.name)
        from public.accreditation_procedures ap
      ), '[]'::jsonb)
    ),
    'modelTasks', coalesce((
      select jsonb_agg(jsonb_build_object('phase', phase, 'item', coalesce(item, ''), 'process', process) order by sort_order)
      from public.roadmap_task_templates
    ), '[]'::jsonb),
    'purchaseItems', coalesce((select jsonb_agg(item order by sort_order, item) from public.purchase_item_templates), '[]'::jsonb),
    'admin', case when v_is_admin then jsonb_build_object(
      'tenants', coalesce((
        select jsonb_agg(jsonb_build_object('id', t.id, 'code', t.code, 'name', t.name, 'status', t.status) order by t.name)
        from public.tenants t
      ), '[]'::jsonb),
      'users', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', u.id, 'name', u.name, 'email', u.email, 'platformRole', u.role, 'active', u.active,
          'memberships', coalesce((
            select jsonb_agg(jsonb_build_object('tenantId', tm.tenant_id, 'tenantName', t.name, 'role', tm.role, 'active', tm.active) order by t.name)
            from public.tenant_memberships tm join public.tenants t on t.id = tm.tenant_id where tm.user_id = u.id
          ), '[]'::jsonb)
        ) order by u.name, u.email)
        from public.app_users u
      ), '[]'::jsonb),
      'requests', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', mr.id, 'tenantId', mr.tenant_id, 'tenantName', t.name, 'moduleCode', mr.module_code,
          'moduleName', mc.name, 'status', mr.status, 'notes', coalesce(mr.notes, ''),
          'requestedBy', u.name, 'createdAt', mr.created_at
        ) order by mr.created_at desc)
        from public.module_requests mr
        join public.tenants t on t.id = mr.tenant_id
        join public.module_catalog mc on mc.code = mr.module_code
        join public.app_users u on u.id = mr.requested_by
      ), '[]'::jsonb)
    ) else null end
  );
end;
$$;

revoke execute on function public.get_app_data(text) from public, anon, authenticated;
grant execute on function public.get_portal_data(text) to anon, authenticated;

create or replace function public.admin_create_portal_user(
  p_token text,
  p_email text,
  p_name text,
  p_password text,
  p_tenant_id uuid default null,
  p_role text default 'user'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid;
  v_user_id uuid;
begin
  v_admin_id := public.require_platform_admin(p_token);
  if length(trim(coalesce(p_password, ''))) < 8 then
    raise exception 'A senha precisa ter pelo menos 8 caracteres' using errcode = '22023';
  end if;
  if p_role not in ('franchise_admin', 'manager', 'user') then
    raise exception 'Papel de franquia inválido' using errcode = '22023';
  end if;

  insert into public.app_users (email, name, password_hash, role, active)
  values (lower(trim(p_email)), trim(p_name), extensions.crypt(p_password, extensions.gen_salt('bf')), 'tenant_user', true)
  returning id into v_user_id;

  if p_tenant_id is not null then
    insert into public.tenant_memberships (tenant_id, user_id, role)
    values (p_tenant_id, v_user_id, p_role);
  end if;

  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_admin_id, 'app_user', v_user_id::text, 'admin_create', jsonb_build_object('tenantId', p_tenant_id, 'role', p_role));

  return jsonb_build_object('ok', true, 'userId', v_user_id);
end;
$$;

create or replace function public.admin_set_user_access(
  p_token text,
  p_user_id uuid,
  p_tenant_id uuid,
  p_role text,
  p_active boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid;
begin
  v_admin_id := public.require_platform_admin(p_token);
  if p_role not in ('franchise_admin', 'manager', 'user') then
    raise exception 'Papel de franquia inválido' using errcode = '22023';
  end if;
  insert into public.tenant_memberships (tenant_id, user_id, role, active)
  values (p_tenant_id, p_user_id, p_role, p_active)
  on conflict (tenant_id, user_id) do update set role = excluded.role, active = excluded.active;
  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_admin_id, 'tenant_membership', p_tenant_id::text || ':' || p_user_id::text, 'upsert', jsonb_build_object('role', p_role, 'active', p_active));
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.admin_set_tenant_module(
  p_token text,
  p_tenant_id uuid,
  p_module_code text,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_id uuid;
begin
  v_admin_id := public.require_platform_admin(p_token);
  if p_status not in ('locked', 'requested', 'active', 'suspended') then
    raise exception 'Status de módulo inválido' using errcode = '22023';
  end if;
  insert into public.tenant_modules (tenant_id, module_code, status, enabled_at, enabled_by)
  values (p_tenant_id, p_module_code, p_status, case when p_status = 'active' then now() else null end, case when p_status = 'active' then v_admin_id else null end)
  on conflict (tenant_id, module_code) do update
    set status = excluded.status, enabled_at = excluded.enabled_at, enabled_by = excluded.enabled_by;
  if p_status = 'active' then
    update public.module_requests set status = 'approved', reviewed_by = v_admin_id, reviewed_at = now()
    where tenant_id = p_tenant_id and module_code = p_module_code and status = 'pending';
  end if;
  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_admin_id, 'tenant_module', p_tenant_id::text || ':' || p_module_code, 'set_status', jsonb_build_object('status', p_status));
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.request_tenant_module(
  p_token text,
  p_tenant_id uuid,
  p_module_code text,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_request_id bigint;
begin
  v_user_id := public.require_app_user(p_token);
  if not public.can_access_tenant(v_user_id, p_tenant_id) then
    raise exception 'Você não possui acesso a esta franquia' using errcode = '42501';
  end if;
  if p_module_code = 'business' then
    raise exception 'O módulo de Negócios já faz parte do plano padrão' using errcode = '22023';
  end if;
  if exists (select 1 from public.tenant_modules where tenant_id = p_tenant_id and module_code = p_module_code and status = 'active') then
    raise exception 'Este módulo já está ativo' using errcode = '22023';
  end if;
  insert into public.module_requests (tenant_id, module_code, requested_by, notes)
  select p_tenant_id, p_module_code, v_user_id, p_notes
  where not exists (
    select 1 from public.module_requests
    where tenant_id = p_tenant_id and module_code = p_module_code and status = 'pending'
  )
  returning id into v_request_id;
  update public.tenant_modules set status = 'requested'
  where tenant_id = p_tenant_id and module_code = p_module_code and status <> 'active';
  return jsonb_build_object('ok', true, 'requestId', v_request_id);
end;
$$;

grant execute on function public.admin_create_portal_user(text, text, text, text, uuid, text) to anon, authenticated;
grant execute on function public.admin_set_user_access(text, uuid, uuid, text, boolean) to anon, authenticated;
grant execute on function public.admin_set_tenant_module(text, uuid, text, text) to anon, authenticated;
grant execute on function public.request_tenant_module(text, uuid, text, text) to anon, authenticated;

create or replace function public.update_task_status(p_token text, p_task_id text, p_status text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_unit_id text;
begin
  v_user_id := public.require_app_user(p_token);
  select unit_id into v_unit_id from public.roadmap_tasks where id = p_task_id;
  perform public.require_unit_access(v_user_id, v_unit_id, true);
  update public.roadmap_tasks set status = p_status where id = p_task_id;
  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_user_id, 'roadmap_task', p_task_id, 'update_status', jsonb_build_object('status', p_status));
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.update_purchase_status(p_token text, p_purchase_id text, p_status text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_unit_id text;
begin
  v_user_id := public.require_app_user(p_token);
  select unit_id into v_unit_id from public.purchase_items where id = p_purchase_id;
  perform public.require_unit_access(v_user_id, v_unit_id, true);
  update public.purchase_items set status = p_status where id = p_purchase_id;
  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_user_id, 'purchase_item', p_purchase_id, 'update_status', jsonb_build_object('status', p_status));
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.update_unit_operational_record(
  p_token text, p_unit_id text, p_record_type text, p_record_id text, p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_record public.unit_operational_records%rowtype;
begin
  v_user_id := public.require_app_user(p_token);
  perform public.require_unit_access(v_user_id, p_unit_id, true);
  insert into public.unit_operational_records (unit_id, record_type, record_id, payload, hidden)
  values (p_unit_id, p_record_type, p_record_id, coalesce(p_payload, '{}'::jsonb), false)
  on conflict (unit_id, record_type, record_id) do update set payload = excluded.payload, hidden = false
  returning * into v_record;
  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_user_id, 'unit_operational_record', p_unit_id || ':' || p_record_type || ':' || p_record_id, 'update', v_record.payload);
  return jsonb_build_object('unitId', v_record.unit_id, 'recordType', v_record.record_type, 'recordId', v_record.record_id, 'hidden', v_record.hidden) || v_record.payload;
end;
$$;

create or replace function public.delete_unit_operational_record(
  p_token text, p_unit_id text, p_record_type text, p_record_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
begin
  v_user_id := public.require_app_user(p_token);
  perform public.require_unit_access(v_user_id, p_unit_id, true);
  insert into public.unit_operational_records (unit_id, record_type, record_id, hidden)
  values (p_unit_id, p_record_type, p_record_id, true)
  on conflict (unit_id, record_type, record_id) do update set hidden = true;
  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_user_id, 'unit_operational_record', p_unit_id || ':' || p_record_type || ':' || p_record_id, 'hide', jsonb_build_object('hidden', true));
  return jsonb_build_object('unitId', p_unit_id, 'recordType', p_record_type, 'recordId', p_record_id, 'hidden', true);
end;
$$;

create or replace function public.update_accreditation_record(
  p_token text, p_unit_id text, p_procedure_id text, p_status text,
  p_request_date date default null, p_approval_date date default null,
  p_owner_name text default null, p_attachments text default null, p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_record public.accreditation_statuses%rowtype;
begin
  v_user_id := public.require_app_user(p_token);
  perform public.require_unit_access(v_user_id, p_unit_id, true);
  insert into public.accreditation_statuses (
    procedure_id, unit_id, status, request_date, approval_date, owner_name, attachments, notes, hidden
  ) values (
    p_procedure_id, p_unit_id, p_status, p_request_date, p_approval_date, p_owner_name, p_attachments, p_notes, false
  )
  on conflict (procedure_id, unit_id) do update set
    status = excluded.status, request_date = excluded.request_date, approval_date = excluded.approval_date,
    owner_name = excluded.owner_name, attachments = excluded.attachments, notes = excluded.notes, hidden = false
  returning * into v_record;
  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_user_id, 'accreditation_status', p_unit_id || ':' || p_procedure_id, 'update', jsonb_build_object('status', p_status));
  return jsonb_build_object('ok', true, 'unitId', v_record.unit_id, 'procedureId', v_record.procedure_id);
end;
$$;

create or replace function public.delete_accreditation_record(p_token text, p_unit_id text, p_procedure_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
begin
  v_user_id := public.require_app_user(p_token);
  perform public.require_unit_access(v_user_id, p_unit_id, true);
  update public.accreditation_statuses set hidden = true
  where unit_id = p_unit_id and procedure_id = p_procedure_id;
  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_user_id, 'accreditation_status', p_unit_id || ':' || p_procedure_id, 'hide', jsonb_build_object('hidden', true));
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.create_unit_from_template(
  p_token text, p_city text, p_state text, p_franchisee text, p_opening_date date,
  p_owner_name text default null, p_priority text default 'Normal'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_unit_id text;
  v_name text;
  v_tenant_id uuid;
begin
  v_user_id := public.require_platform_admin(p_token);
  v_unit_id := public.slugify(concat_ws('-', p_city, p_state));
  v_name := trim(concat(upper(p_city), ' ', upper(coalesce(p_state, ''))));
  if exists (select 1 from public.units where id = v_unit_id) then
    v_unit_id := v_unit_id || '-' || substr(encode(extensions.gen_random_bytes(3), 'hex'), 1, 6);
  end if;
  insert into public.tenants (code, name) values (v_unit_id, v_name) returning id into v_tenant_id;
  insert into public.units (id, tenant_id, name, city, state, franchisee, opening_date, source_file, owner_name, priority)
  values (v_unit_id, v_tenant_id, v_name, initcap(trim(p_city)), upper(trim(p_state)), p_franchisee, p_opening_date, 'Criado no sistema', p_owner_name, p_priority);
  insert into public.roadmap_tasks (id, unit_id, template_id, item, phase, process, status, sort_order)
  select v_unit_id || '-task-' || sort_order, v_unit_id, id, item, phase, process, 'Pendente', sort_order
  from public.roadmap_task_templates order by sort_order;
  insert into public.purchase_items (id, unit_id, template_id, item, status, sort_order)
  select v_unit_id || '-purchase-' || sort_order, v_unit_id, id, item, 'Pendente', sort_order
  from public.purchase_item_templates order by sort_order;
  insert into public.accreditation_units (id, name, owner_name)
  values (v_unit_id, upper(trim(p_city)), p_owner_name);
  insert into public.tenant_modules (tenant_id, module_code, status, enabled_at, enabled_by)
  select v_tenant_id, code, case when default_enabled then 'active' else 'locked' end,
         case when default_enabled then now() else null end,
         case when default_enabled then v_user_id else null end
  from public.module_catalog where active = true;
  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_user_id, 'unit', v_unit_id, 'create_from_template', jsonb_build_object('tenantId', v_tenant_id, 'city', p_city, 'state', p_state));
  return jsonb_build_object('ok', true, 'unitId', v_unit_id, 'tenantId', v_tenant_id);
end;
$$;

create or replace function public.delete_franchise_unit(p_token text, p_unit_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_tenant_id uuid;
begin
  v_user_id := public.require_platform_admin(p_token);
  select tenant_id into v_tenant_id from public.units where id = p_unit_id;
  delete from public.accreditation_statuses where unit_id = p_unit_id;
  delete from public.accreditation_units where id = p_unit_id;
  delete from public.unit_operational_records where unit_id = p_unit_id;
  delete from public.units where id = p_unit_id;
  if v_tenant_id is not null and not exists (select 1 from public.units where tenant_id = v_tenant_id) then
    delete from public.tenants where id = v_tenant_id;
  end if;
  insert into public.audit_events (user_id, entity_type, entity_id, action, payload)
  values (v_user_id, 'unit', p_unit_id, 'delete', jsonb_build_object('tenantId', v_tenant_id));
  return jsonb_build_object('ok', true, 'unitId', p_unit_id);
end;
$$;
